# This is the config file for BasicQuests.
# This config was generated for version 0.2.2


# GENERAL

# amount of quests a player holds at a time
# recommended values: min = 3, max = 6
quest-amount: 3

# times a player is allowed to skip a quest. (resets every day)
skips-per-day: 1

# broadcasts a message to everyone if a player completes a quest
broadcast-on-quest-complete: false

# broadcasts a message to everyone if a player completes a quest
show-quest-progress-in-chat: true



# QUEST GENERATION

# factor for the value of rewards
reward-factor: 1.0

# factor for the quantities in a quest - eg. the amounts of zombies to kill
# recommended values: min = 0.5, max = 3.0
quantity-factor: 1.0

# Increase the quantities in quests according to a players play time.
increase-quantity-by-playtime: true

# factor when a player joins the game
start-factor: 0.4

# factor when a player reaches <max-amount-hours> hours of playtime
max-factor: 3.0

# hours of play time at which a player receives quests with max quantities
max-amount-hours: 60

# Chance of duplicate quests [0.0 - 1.0]
# 0.0: no duplicate quests will appear (not recommended when quest-amount is above 4)
# 1.0: players active quests have no influence on generation of new quests
duplicate-quest-chance: 0.3



# REWARDS
# choose what type of reward you would like to be generated for quests
# if multiple types are set to true new quests will have a reward type chosen randomly

# enable items as rewards
item-rewards: true

# enable xp as a reward
xp-rewards: false

# enable money as a reward (requires an economy plugin to be hooked up via Vault)
money-rewards: false



# ECONOMY

# factor for money rewards
# adjust this to the value of money on your server.
money-factor: 1.0
