name: BasicQuests
version: 0.3.2
main: de.stamme.basicquests.BasicQuestsPlugin
description: Randomly generates basic quests with rewards for players.

author: Tonnanto
api-version: "1.16"
softdepend: [Vault, Essentials, PlaceholderAPI]

commands:
  basicquests:
    description: BasicQuests Command
    aliases: ["quests"]

permissions:
  basicquests:
    default: true
    description: Lets player use basicquests commands
  basicquests.show:
    default: true
    description: Lets players view their quests
    children:
      rewards: true
      scoreboard: true
  basicquests.reward:
    default: true
    description: Lets players receive their rewards
  basicquests.skip:
    default: true
    description: Lets players skip a limitied number of quests per day. Number can be configured in config.yml.
    children:
      quests.skip.unlimited: false
      quests.skip.forothers: false
  basicquests.reset:
    default: op
    description: lets players reset quests
    children:
      quests.reset.forothers: true
      quests.reset.global: true
  basicquests.complete:
    default: op
    description: Allows a player to use /quests complete.
    children:
      quests.complete.forothers: true
  basicquests.update:
    default: op
    description: Allows a user or the console to check for BasicQuests updates
  basicquests.reload:
    default: op
    description: Allows a user to reload the config
