name: BasicQuests
version: 0.3.2
main: de.stamme.basicquests.BasicQuestsPlugin
description: Randomly generates basic quests with rewards for players.

author: Tonnanto
api-version: "1.16"
softdepend: [Vault, Essentials, PlaceholderAPI]

commands:
  basicquests:
    description: BasicQuests Command
    aliases: ["quests", "bq"]

permissions:
  basicquests:
    default: true
    description: Lets player use basicquests commands
  basicquests.show:
    default: true
    description: Lets players view their quests
  basicquests.scoreboard:
    default: true
    description: Lets players use the scoreboard to display quests
  basicquests.reward:
    default: true
    description: Lets players receive their rewards
  basicquests.skip:
    default: true
    description: Lets players skip a limitied number of quests per day. Number can be configured in config.yml
  basicquests.skip.unlimited:
    default: op
    description: Lets players skip unlimited quests
  basicquests.skip.forothers:
    default: op
    description: Lets players skip quests for other players
  basicquests.reset:
    default: op
    description: lets players reset quests
    children:
      basicquests.reset.forothers: true
      basicquests.reset.global: true
  basicquests.complete:
    default: op
    description: Lets players complete quests via command
    children:
      basicquests.complete.forothers: true
  basicquests.update:
    default: op
    description: Lets a user or the console to check for BasicQuests updates
  basicquests.reload:
    default: op
    description: Lets a user use the reload command
